#!/bin/sh

echo >&2
echo "F97" >&2
echo >&2


FORTRAN_LINE=$@
ORIG_FORTRAN_LINE=$@
echo $FORTRAN_LINE >&2

COMPILE_TARGET=0
# 1 to object
# 2 to shared library

OBJECT_NAME=""

while getopts ":o:I:L:gO:c:s:f:" opt; do
	case $opt in
	o)
		#change -o to generate bitcode
		echo $OPTARG >&2
		FORTRAN_LINE=$(echo $FORTRAN_LINE | sed -e "s/-o $OPTARG/ -S -flto -o $OPTARG.ll/g")
		OBJECT_NAME=$OPTARG
		IS_OBJECT_FILE=$(echo $OPTARG | grep '\.bc$')
		if [ $IS_OBJECT_FILE ] ; then
			COMPILE_TARGET=1
		fi
		
		
		;;
	esac
done

CHECK_OBJECT_NAME=0

if [ -z $OBJECT_NAME ] ; then
	OBJECT_NAME_WITHOUT_O=$(echo $FORTRAN_LINE | grep -o '\-c [^- ]*' | cut -b4- | cut -d'.' -f1)

	if [ -n $OBJECT_NAME_WITHOUT_O ] ; then
		OBJECT_NAME_WITHOUT_O=$(echo $FORTRAN_LINE | grep -o ' [^- ]*$' | cut -d'.' -f1)
	fi

	OBJECT_NAME="$OBJECT_NAME_WITHOUT_O"
	FORTRAN_LINE="-S -flto -o $OBJECT_NAME.ll $FORTRAN_LINE"
	CHECK_OBJECT_NAME=1
fi
#	echo gfortran-4.8 -fplugin=/usr/lib/gcc/x86_64-linux-gnu/4.8/plugin/dragonegg.so $ORIG_FORTRAN_LINE
#	gfortran-4.8 -fplugin=/usr/lib/gcc/x86_64-linux-gnu/4.8/plugin/dragonegg.so $ORIG_FORTRAN_LINE
#else
	echo "Objectname $OBJECT_NAME" >&2

	echo gfortran-4.8 -fno-underscoring -fplugin=/usr/lib/gcc/x86_64-linux-gnu/4.8/plugin/dragonegg.so $FORTRAN_LINE >&2
	gfortran-4.8 -fno-underscoring -fplugin=/usr/lib/gcc/x86_64-linux-gnu/4.8/plugin/dragonegg.so $FORTRAN_LINE  >&2
	sed -i 's/target triple = \"x86_64--linux-gnu\"/target triple = \"x86_64-pc-linux-gnu\"/' $OBJECT_NAME.ll
	sed -i 's/!0 = metadata !{i32 1, metadata !\"Debug Info Version\", i32 1}/!0 = metadata !{i32 2, metadata !\"Debug Info Version\", i32 1}/' $OBJECT_NAME.ll

	
	# check whether file is an exec

	llvm-as -o $OBJECT_NAME $OBJECT_NAME.ll

if [ $CHECK_OBJECT_NAME -eq 1 ] ; then
	IS_EXEC=$(grep 'define i32 @main(i32 %\w*, i8\*\* %av)' $OBJECT_NAME.ll)
	if [ $IS_EXEC ] ; then
		echo "file has main" >&2
		mv $OBJECT_NAME $OBJECT_NAME_WITHOUT_O
	else
		mv $OBJECT_NAME $OBJECT_NAME.bc
		echo "final name $OBJECT_NAME".bc >&2
	fi
fi
#llc -filetype=obj -relocation-model=pic $OBJECT_NAME.bc -o $OBJECT_NAME
#fi
echo >&2
echo "----------" >&2
echo >&2
